# ########################## # 
#                            #
#  Skyoseasons Plugin YAML   #
#                            #
#   No configuration here !  #
#                            #
# ########################## #
#                            #
#  You can change 'default'  #
#      in 'permissions'      #
#    if you don't have a     #
#     permission plugin.     #
#                            #
# ########################## #

name: Skyoseasons
main: com.skyost.seasons.SeasonsPlugin
description: Seasons in Minecraft !
version: 1.0
author: Skyost
website: http://dev.bukkit.org/bukkit-plugins/skyoseasons/
commands:
 seasons:
  aliases: season
  description: Main command of Skyoseasons.
  usage: /season(s) to display the current season and /season(s) set <Season> to set the current season to <Season>.
  permission: skyoseasons.view
permissions:
  skyoseasons.view:
   default: true
   description: Allow you to display the current season.
  skyoseasons.set:
   default: op
   description: Allow you to set the current season.