# ########################## # 
#                            #
#  Skyoseasons Plugin YAML   #
#                            #
#   No configuration here !  #
#                            #
# ########################## #
#                            #
#  You can change 'default'  #
#      in 'permissions'      #
#    if you don't have a     #
#     permission plugin.     #
#                            #
# ########################## #
#                            #
#        .:By Skyost:.       #
#                            #
# ########################## #

name: Skyoseasons
main: fr.skyost.seasons.Skyoseasons
description: Add seasons to your Bukkit server !
version: 4.1.1
softdepend: [ProtocolLib]
author: Skyost
website: https://dev.bukkit.org/bukkit-plugins/skyoseasons/
commands:
 skyoseasons:
  aliases: [season, seasons]
  description: Main command of Skyoseasons.
  usage: /skyoseasons <day <new-day>|month <new-month>|season <new-season>|season-month <new-season-month>|year <new-year>>
 calendar:
  aliases: [cal]
  description: Opens the calendar.
  permission: skyoseasons.calendar
  usage: /calendar <world>
permissions:
  skyoseasons.calendar:
   default: true
   description: Allows you to open the calendar or display the current day / month / season / year.
  skyoseasons.calendar.setday:
   default: op
   description: Allows you to set the current day. Requires skyoseasons.calendar.
  skyoseasons.calendar.setmonth:
   default: op
   description: Allows you to set the current month. Requires skyoseasons.calendar.
  skyoseasons.calendar.setseason:
   default: op
   description: Allows you to set the current season. Requires skyoseasons.calendar.
  skyoseasons.calendar.setseasonmonth:
   default: op
   description: Allows you to set the month of the current season. Requires skyoseasons.calendar.
  skyoseasons.calendar.setyear:
   default: op
   description: Allows you to set the current year. Requires skyoseasons.calendar.